### ISSUE TITLE
Documentation website gives 404

### ISSUE THREAD

**Issue by thiagotrennepohl** [involvestecnologia/violin#7]
Hello everyone, congratz for this great repo!

Is it just me or the docs lead to a 404 page?
![image](https://user-images.githubusercontent.com/12124856/69420134-643b2880-0d1e-11ea-9799-1717e87eb7c5.png)

Thanks.

**Comment by nbfontana** [comment]
Hi @thiagotrennepohl!

We are creating a new e-mail account to migrate de url and also add the project to the npm site.

Everything will be ready to use soon. We'll let you know.

**Comment by nbfontana** [comment]
@thiagotrennepohl https://violin-ui.netlify.com :shipit:
